"""Writes research/pilot_e/results.md and results.json from the analysis dict (repair round r1)."""
import json, math, os
from common import LAW9, PHYS7, PRIMARY, LEVELS, EXTRA_CODES, HERE


def f1(x):
    if x is None:
        return 'n/a'
    if isinstance(x, float) and (math.isinf(x) or math.isnan(x)):
        return str(x)
    return '%.1f' % x


def f3(x):
    if x is None:
        return 'n/a'
    if isinstance(x, float) and (math.isinf(x) or math.isnan(x)):
        return str(x)
    return '%.3f' % x


def table(header, rows):
    out = ['| ' + ' | '.join(header) + ' |', '|' + '---|' * len(header)]
    for r in rows:
        out.append('| ' + ' | '.join(str(x) for x in r) + ' |')
    return '\n'.join(out)


def gk(d, k):
    return d[k] if k in d else d[str(k)]


def fired(x):
    return 'FIRED' if x else 'not fired'


def k1_line(name, k):
    s = '**%s**: %s (criterion a: %s, criterion b: %s); min rho = %s; tops = %s' % (
        name, fired(k['fired']), k['fired_a'], k['fired_b'], f3(k['min_rho']), json.dumps(k['tops']))
    if k['flips']:
        fl = sorted({(x['a'], x['b'], x['top_a'], round(x['Phi_b_top_a'], 1), round(x['max_b'], 1), x['top_b']) for x in k['flips']})
        s += '; flips (a, b, top_a, Phi_b(top_a), max Phi_b, top_b): ' + '; '.join(str(x) for x in fl)
    return s


def write(R, md_path, json_path):
    L = []
    v = R['verdict']
    T = R['tables']
    K1 = R['K1']
    L.append('# Pilot E-v1 results ("two kinds of compression"), repair round r1\n')
    L.append('Frozen spec: `pilot_v1/SPEC.md`, sha256 `%s`. All numbers regenerated by `python3 pilot_v1/run_all.py`. '
             'The pre-repair outputs are kept in `pilot_v1/orig_v1/`. Every change is listed in `pilot_v1/DEVIATIONS.txt` '
             '(section R) and at the end of this file.\n' % R['spec_sha256'])
    L.append('Main pipeline switches: `%s`.\n' % json.dumps(R['cfg_main']))
    # ------------------------------------------------------------ verdict
    L.append('## Verdict (decisive statistics = spec definitions on the repaired pipeline)\n')
    L.append(table(['item', 'result'], [
        ['K1 (code dependence)', fired(v['K1']['fired'])],
        ['K1 sub-tests fired (spec: primary C1-C4 / machine D0-D2 / precision at D1; uncharged)', ', '.join(v['K1']['subtests']) or '-'],
        ['K1-fragile label', v['K1']['fragile']],
        ['K2-deg-R (Track R degeneracy)', fired(v['K2_deg_R'])],
        ['K2-deg-G (Track G degeneracy)', fired(v['K2_deg_G'])],
        ['K2-collapse (literal)', v['K2_collapse']],
        ['validity gate', json.dumps(v['K2_collapse_gate'])],
        ['constraint-type physical laws, measured (primary setting, spec miner)', v['constraint_type_physical_laws']],
        ['K2-collapse (operative; spec section 8 fallback when the gate fails)', v['K2_collapse_operative']],
        ['constraint-type laws, operative', v['constraint_type_operative']],
        ['K2 overall', fired(v['K2_overall'])],
        ['candidate', v['candidate']],
        ['hypothesis (iii)', 'REFUTED' if R['hypothesis_iii']['refuted'] else 'not refuted'],
    ]))
    if v.get('note_indeterminate'):
        L.append('\nNote: ' + v['note_indeterminate'])
    L.append('\n### Interpretation / alternative-setting sensitivity (reported, not decisive)\n')
    L.append(table(['item', 'result'], [
        ['K1-primary with EC decoder charged', fired(v['K1']['primary_charged_fired'])],
        ['K1-machine with EC decoder charged at D0/D1', fired(v['K1']['machine_charged_fired'])],
        ['K1-machine with D2M (D2 + coordinate map) instead of D2', fired(K1['machine_D2M']['fired'])],
        ['K1-precision at D0 / D1 / D2', ' / '.join(fired(v['K1']['precision_by_level'][lv]) for lv in LEVELS)],
        ['K1 extended codes C1-C4 + C6, C7, C9 (D1, uncharged)', fired(v['K1']['extended_D1_uncharged_fired'])],
        ['K1-primary with the added baseline alternatives switched off (noaddbase)', fired(K1['noaddbase_primary']['fired'])],
        ['K1-machine, noaddbase', fired(K1['noaddbase_machine']['fired'])],
        ['K1-primary on per-system normalised Phi', fired(K1['normalized']['primary']['fired'])],
        ['K1-primary leave-one-system-out: still fires after dropping', '%d of 24 systems; not fired after dropping %s' % (
            K1['loso']['primary']['n_fired'], [s for s, x in K1['loso']['primary']['per_drop'].items() if not x['fired']])],
        ['K1-machine leave-one-system-out: still fires after dropping', '%d of 24 systems; not fired after dropping %s' % (
            K1['loso']['machine']['n_fired'], [s for s, x in K1['loso']['machine']['per_drop'].items() if not x['fired']])],
        ['7.3 with a family-aware count model (famP + famG*n^3) instead of the spec model',
         'EC count-degenerate: %s' % (R['EC_scaling'] or {}).get('family_model_would_fire_famP, famG*n^3')],
        ['K2-deg-R with EC = symmetric part only (EC_sym)', fired(v['K2_deg_R_ECsym_alternative'])],
        ['K2 overall if INDETERMINATE counted as not fired (pre-repair C18 reading)', fired(v['K2_overall_if_indeterminate_counts_as_not_fired'])],
    ]))
    # ------------------------------------------------------------ reading notes (numbers pulled from R)
    prim = R['K2_collapse']['primary_D1_charged']
    pos = prim['POS']['detail']
    ecs = R.get('EC_scaling') or {}
    L.append('\n### Reading notes\n')
    L.append('- Validity gate: POS can save at most max(#sign-known constants) - L(POS) = max(%d, %d) - %.0f bits in C4 '
             'against tau_C4 = %.1f, so the POS criterion cannot pass on this corpus; K2-collapse is INDETERMINATE by '
             'construction, and the operative verdict is the spec fallback (R16).' % (
                 pos['n_sign_off']['empty'], pos['n_sign_off']['LAW9'], pos['L_POS'], prim['tau']['C4']))
    L.append('- The generic miners recover only part of a known abbreviation: DIST recovery (share of V_mid removed) is %s '
             '(spec miner) and %s (miner v2) at the primary setting, so miner-based "constraint" labels of substitution laws '
             'are instrument-limited.' % (
                 json.dumps({c: (round(x, 2) if x is not None else None) for c, x in R['DIST_recovery']['primary_D1_charged'].items()}),
                 json.dumps({c: (round(x, 2) if x is not None else None) for c, x in R['DIST_recovery']['v2_primary_D1_charged'].items()})))
    L.append('- EC\'s residual surplus at D2 on family G comes from n explicit residuals vs one L whose decoder loops over '
             'coordinates; D2M (a generic map) lowers it but does not remove it (C1 Phi_EC: D2 %s, D2M %s).' % (
                 f1(T['C1-D2-B16']['values']['EC']['Phi']), f1(T['C1-D2M-B16']['values']['EC']['Phi'])))
    if ecs:
        L.append('- 7.3: the spec regression (additive in n, pairs, P, family) does not fit, but a family-aware model '
                 '(famP + famG*n^3) has LOSO CV-R2 %s; EC\'s surplus is -1 bit on every family-P system and grows ~n^3 on '
                 'N-link pendulums.' % json.dumps({c: round(ecs['per_code'][c]['fits_dedup']['famP, famG*n^3']['cv_r2'], 3) for c in PRIMARY}))
    L.append('- Track R: I equals codim x (b + log2(2 pi)/2) exactly in R1 (R2 of I ~ codim = %s spec, %s EC_sym); the '
             'per-cell R2 against the frozen r_fk proxy is lower only because the proxy is not the codimension.' % (
                 f3(R['K2_deg_R']['percell']['R1']['r2_vs_codim']), f3(R['K2_deg_R_ECsym']['percell']['R1']['r2_vs_codim'])))
    # ------------------------------------------------------------ unit tests
    L.append('\n## Unit tests (section 9)\n')
    L.append(table(['test', 'passed', 'detail'], [[k, d['passed'], json.dumps(d['detail'], default=str)[:220]]
                                                  for k, d in sorted(R['unit_tests'].items())]))
    L.append('\nsympy CSE temps found in the 18 decoder-rule sides: %s (so statement CSE leaves dec_c unchanged).' % R.get('dec_rules_cse_temps'))
    # ------------------------------------------------------------ Track G values
    L.append('\n## Track G: per-law values (bits; positive = the law shortens the corpus)\n')
    L.append('Phi = exact Shapley over the 512-theory lattice; add = L(0)-L({f}); loo = L(LAW9\\f)-L(LAW9); '
             'mid = (add+loo)/2. Miner off, EC decoder uncharged unless stated.\n')
    # side-by-side
    o = R.get('orig_v1', {}).get('tables', {})
    if o:
        L.append('\n### Repaired vs pre-repair Phi (D1, miner off, uncharged)\n')
        rows = []
        for f in LAW9:
            row = [f]
            for c in PRIMARY:
                t = '%s-D1-B16' % c
                row.append('%s -> %s' % (f1(o[t]['values'][f]['Phi']), f1(T[t]['values'][f]['Phi'])))
            row.append('%s -> %s' % (f1(o['C1-D1-B16']['law_single'][f]), f1(T['C1-D1-B16']['law_single'][f])))
            rows.append(row)
        L.append(table(['law'] + ['%s Phi (pre -> repaired)' % c for c in PRIMARY] + ['L_C1(f) (pre -> repaired)'], rows))
    abl = [t for t in T if '-abl-' in t]
    if abl:
        L.append('\n### Ablation of each repair (C1, D1, Phi uncharged; each column switches ONE repair off, except the all-repairs-off column)\n')
        names = sorted(abl)
        L.append(table(['law', 'repaired'] + [('all repairs off' if n.endswith('all_off') else n.split('-abl-')[1] + ' off') for n in names],
                       [[f, f1(T['C1-D1-B16']['values'][f]['Phi'])] + [f1(T[n]['values'][f]['Phi']) for n in names] for f in LAW9]))
    tags = ['C1-D1-B16', 'C2-D1-B16', 'C3-D1-B16', 'C4-D1-B16', 'C1-D0-B16', 'C2-D0-B16', 'C3-D0-B16', 'C4-D0-B16',
            'C1-D2-B16', 'C2-D2-B16', 'C3-D2-B16', 'C4-D2-B16', 'C1-D2M-B16', 'C2-D2M-B16', 'C3-D2M-B16', 'C4-D2M-B16',
            'C4-D1-B8', 'C4-D1-B32', 'C4-D0-B8', 'C4-D0-B32', 'C4-D2-B8', 'C4-D2-B32', 'C5-D0-B16', 'C5-D1-B16', 'C5-D2-B16']
    tags += ['%s-%s-B16' % (c, lv) for lv in LEVELS for c in EXTRA_CODES]
    tags += ['%s-%s-B16-noaddbase' % (c, lv) for lv in LEVELS for c in PRIMARY]
    for tag in tags:
        if tag not in T:
            continue
        t = T[tag]
        L.append('\n### %s   (L(S|0) = %s, L(S|LAW9) = %s, dec(EC) = %s)\n' % (tag, f1(t['L0']), f1(t['Lfull']), f1(t['dec'])))
        rows = []
        for f in LAW9:
            x = t['values'][f]
            xc = t['values_charged'][f]
            rows.append([f, f1(x['Phi']), f1(x['add']), f1(x['loo']), f1(x['mid']), f1(xc['Phi']), f1(xc['mid']),
                         f1(t['law_single'][f])])
        L.append(table(['law', 'Phi', 'V_add', 'V_loo', 'V_mid', 'Phi (EC charged)', 'V_mid (charged)', 'L_c(f)'], rows))
    c8 = K1['C8']
    L.append('\n### C8 (lzma proxy on C1-chosen D1 representations)  L(S|0)=%s, L(S|LAW9)=%s\n' % (f1(c8['L0']), f1(c8['Lfull'])))
    L.append(table(['law', 'Phi_C8'], [[f, f1(c8['Phi'][f])] for f in LAW9]))
    L.append('\nSpearman C8 vs primary codes: %s; top law C8: %s' % (json.dumps({k: round(x, 3) for k, x in c8['spearman'].items()}), c8['top']))
    # ------------------------------------------------------------ K1
    L.append('\n## K1 (section 6)\n')
    L.append('Decisive (spec): ' + '; '.join(fired(K1[k]['fired']) + ' ' + k for k in ('primary', 'machine', 'precision')) + '.\n')
    for name in ('primary', 'machine', 'precision'):
        k = K1[name]
        L.append('\n' + k1_line('K1-%s' % name, k))
        L.append('\n' + table(['pair', 'Spearman rho'], [[p, f3(x)] for p, x in k['pairs'].items()]))
    L.append('\n### Reported K1 variants\n')
    for name, k in [('K1-primary, EC charged', K1['primary_charged']), ('K1-machine, EC charged at D0/D1', K1['machine_charged']),
                    ('K1-machine with D2M', K1['machine_D2M']), ('K1-primary, 7 physical laws', K1['primary_7law']),
                    ('K1-primary, noaddbase', K1['noaddbase_primary']), ('K1-machine, noaddbase', K1['noaddbase_machine']),
                    ('K1-primary on per-system normalised Phi', K1['normalized']['primary']),
                    ('K1 extended (normalised Phi)', K1['normalized']['extended'])]:
        L.append('\n' + k1_line(name, k))
    for lv in LEVELS:
        L.append('\n' + k1_line('K1-precision at %s' % lv, K1['precision_all_levels'][lv]))
    for lv, k in K1['primary_by_level'].items():
        L.append('\n' + k1_line('primary codes at %s' % lv, k))
    for c, k in K1['machine_by_code'].items():
        L.append('\n' + k1_line('machine axis in %s' % c, k))
    L.append('\n### Extended code set (C1-C4 + C6 LaTeX tokens, C7 SR binary-operator tokens, C9 global symbol dictionary)\n')
    for key, e in K1['extended'].items():
        L.append('\n' + k1_line('all 7 codes, %s' % key, e['all']))
        for n, kk in e['each_extra_vs_primary'].items():
            L.append('\n  - %s added to C1-C4: %s, top %s, min rho %s, flips %d' % (n, fired(kk['fired']), kk['tops'][n], f3(kk['min_rho']), len(kk['flips'])))
    for c, k in K1['extended_machine'].items():
        L.append('\n' + k1_line('machine axis in %s' % c, k))
    L.append('\n\nPer-system normalised Phi (sum_k phi(f,k)/L_k(0) + phi_ls/mean_k L_k(0)):\n')
    L.append(table(['law'] + list(K1['normalized']['Phi'].keys()),
                   [[f] + [f3(K1['normalized']['Phi'][c][f]) for c in K1['normalized']['Phi']] for f in LAW9]))
    L.append('\n**Leave-one-system-out** (per-system decomposition, miner off): ' + json.dumps(
        {k: dict(n_fired=x['n_fired'], fired_drops=x['fired_drops']) for k, x in K1['loso'].items()}))
    L.append('\n\nLOSO primary, tops per dropped system: ' + json.dumps({s: x['tops'] for s, x in K1['loso']['primary']['per_drop'].items()}))
    b = K1['bootstrap']
    L.append('\n\n**Bootstrap (1000 resamples of systems, per-system decomposition, miner off)**\n')
    for name in ('primary', 'machine'):
        L.append('\n%s: P(top flip) = %s, P(K1 fires) = %s; 95%% CI of rho: %s' % (
            name, f3(b[name]['P_flip']), f3(b[name]['P_fire']),
            json.dumps({k: [round(x[0], 3), round(x[1], 3)] for k, x in b[name]['rho_CI95'].items()})))
    L.append('\n\nC5 vs primary rho = %s.' % json.dumps({k: round(x, 3) for k, x in K1['C5_vs_primary'].items()}))
    if R.get('miner_on_shapley'):
        m = R['miner_on_shapley']
        L.append('\n**Miner-on Shapley (secondary, spec miner, D1)**\n')
        L.append(table(['law'] + PRIMARY, [[f] + [f1(m['Phi_plus'][c][f]) for c in PRIMARY] for f in LAW9]))
        L.append('\nminer-on K1-style test: min rho = %s, tops = %s, flips = %d' % (
            f3(m['K1_test']['min_rho']), json.dumps(m['K1_test']['tops']), len(m['K1_test']['flips'])))
    # ------------------------------------------------------------ K2 deg G
    G = R['K2_deg_G']
    L.append('\n## K2-deg-G (section 7.2)\n')
    L.append(table(['code', 'M1 CV-R2 (LOSO)', 'M1 in-sample R2', 'n cells', 'beta_r', 'beta_u', 'beta_P', 'beta_n',
                    'M1 per-law u slopes CV-R2 (reported)', 'law-level CV-R2 (LOLO)', 'law-level R2'],
                   [[c, f3(G['M1'][c]['cv_r2']), f3(G['M1'][c]['r2']), G['M1'][c]['n'],
                     f3(G['M1'][c]['coef']['beta_r']), f3(G['M1'][c]['coef']['beta_u']), f3(G['M1'][c]['coef']['beta_P']),
                     f3(G['M1'][c]['coef']['beta_n']), f3(G['M1_perlaw'][c]['cv_r2']),
                     f3(G['lawlevel'][c]['cv_r2']), f3(G['lawlevel'][c]['r2'])] for c in PRIMARY]))
    L.append('\nM1 fired: %s; law-level fired: %s; K2-deg-G fired: %s; per-law-slope variant would fire: %s' % (
        G['M1_fired'], G['lawlevel_fired'], G['fired'], G['M1_perlaw_would_fire']))
    # ------------------------------------------------------------ K2 deg R
    tr = R['trackR']
    L.append('\n## Track R and K2-deg-R (sections 1.7, 7.4)\n')
    for title, Rr, cells in (('spec equations (EC: MA symmetric, C = 0, u = 0; LC: first-order condition about r0)', R['K2_deg_R'], tr['cells']),
                             ('reported alternative EC_sym (MA symmetric only)', R['K2_deg_R_ECsym'],
                              [c for c in tr['cells'] if c['law'] != 'EC'] + [c for c in tr['cells_extra'] if c['law'] == 'EC_sym'])):
        L.append('\n### %s\n' % title)
        rmap = {(x['sid'], x['law']): x['r'] for x in Rr['r_vs_codim']}
        L.append(table(['system', 'law', 'N', 'P', 'codim', 'r_fk', 'I_R1(b=4)', 'I_R1(b=8)', 'I_R1(b=16)', 'I_R2', 'I_R3',
                        'R3 lattice codim', 'log2 index', 'I_R4(N=100)', 'I_R4(N=1000)', 'monomial slots', 'resid'],
                       [[c['sid'], c['law'], c['N'], c['P'], c['codim'], rmap.get((c['sid'], c['law'])),
                         f1(gk(c['I_R1'], 4)), f1(gk(c['I_R1'], 8)), f1(gk(c['I_R1'], 16)), f1(c['I_R2']), f1(c['I_R3']),
                         c.get('codim_R3_lattice'), f3(c['log2_index']), f1(gk(c['I_R4'], 100)), f1(gk(c['I_R4'], 1000)),
                         '%d/%d' % (c['monomial_slots'], c['P']), '%.1e' % c['resid']] for c in cells]))
        L.append('\n' + table(['R code', 'per-cell R2 (I ~ beta r, no intercept; centered)', 'uncentered R2', 'beta',
                               'R2 of I ~ beta*codim'],
                              [[n, f3(Rr['percell'][n]['r2']), f3(Rr['percell'][n]['r2_uncentered']), f3(Rr['percell'][n]['beta']),
                                f3(Rr['percell'][n]['r2_vs_codim'])] for n in ('R1', 'R2', 'R3', 'R4')] +
                              [[n + ' (secondary)', f3(x['r2']), f3(x['r2_uncentered']), f3(x['beta']), f3(x['r2_vs_codim'])]
                               for n, x in Rr['secondary'].items()]))
        L.append('\nK2-deg-R fired: %s' % Rr['fired'])
        L.append('\nV^R_c(f) = sum_k I_c(f,k) - L_C1(f):\n')
        L.append(table(['law'] + list(Rr['VR'].keys()), [[f] + [f1(Rr['VR'][n][f]) for n in Rr['VR']] for f in
                                                          ['EC', 'PC', 'LC', 'N3', 'N2', 'HK', 'UG', 'DIST', 'KE']]))
        L.append('\nLaw-level regressions V^R ~ sum r: ' + json.dumps({n: dict(laws=x['laws'], r2=round(x['r2'], 3)) for n, x in Rr['lawlevel'].items()}))
    L.append('\nExcluded cells: ' + json.dumps([(c['sid'], c['law'], round(c['resid'], 4), c['note']) for c in tr['excluded'] + tr['excluded_extra']]))
    L.append('\nReported only: ' + json.dumps([(c['sid'], c['law'], c['codim']) for c in tr['reported_only']]))
    L.append('\nMach block (N2, corpus level): ' + json.dumps(tr['mach']))
    L.append('\nPOS (Track R, reported): ' + json.dumps(tr['pos']))
    # ------------------------------------------------------------ K2 collapse
    L.append('\n## K2-collapse (section 8)\n')
    L.append('Each cell: V_mid / V+_mid / abbreviation share (V_mid - V+_mid) (label; label under the per-use threshold). '
             '"spec miner" = the pre-registered instrument; "v2" = the added stronger miner (AC matching, AC candidates, '
             'output map, run to convergence). D1_charged_sym = every theory may buy the differentiation library once '
             '(min over D1 and D2 + dec).\n')
    for name, st in R['K2_collapse'].items():
        L.append('\n### setting: %s   (tau: %s; per-use pointer: %s)\n' % (
            name, json.dumps({c: round(x, 1) for c, x in st['tau'].items()}),
            json.dumps({c: round(x, 2) for c, x in st.get('pointer', {}).items()})))
        rows = []
        for f in LAW9:
            row = [f]
            for c in PRIMARY:
                x = st['per_code'][c][f]
                row.append('%s / %s / %s (%s; %s)' % (f1(x['V_mid']), f1(x['Vplus_mid']), f1(x['V_mid'] - x['Vplus_mid']),
                                                      x['label'], x.get('label_per_use', '-')))
            row.append(st['labels'][f])
            row.append(st.get('labels_per_use', {}).get(f, '-'))
            rows.append(row)
        L.append(table(['law'] + ['%s' % c for c in PRIMARY] + ['label (>=3 of 4)', 'per-use label'], rows))
        if 'POS' in st:
            p = st['POS']
            L.append('\nPOS (C4): V_mid = %s, V+_mid = %s, label = %s (per-use: %s); detail %s' % (
                f1(p['V_mid']), f1(p['Vplus_mid']), p['label'], p.get('label_per_use'), json.dumps(p['detail'])))
        if 'Phi' in st:
            L.append('\nPhi under this setting: ' + json.dumps({c: {f: round(x, 1) for f, x in st['Phi'][c].items()} for c in PRIMARY}))
    L.append('\n**DIST recovery by the miner** (share of V_mid(DIST) removed by the miner; instrument validity): ' +
             json.dumps({k: {c: (round(x, 3) if x is not None else None) for c, x in d.items()} for k, d in R['DIST_recovery'].items()}))
    if R.get('EC_scaling'):
        E = R['EC_scaling']
        L.append('\n## EC scaling degeneracy (7.3)\n')
        L.append('Duplicates removed from the scaling series (structurally identical to corpus systems): %s\n' % json.dumps(E['duplicates']))
        rows = []
        for c in PRIMARY:
            pc = E['per_code'][c]
            rows.append([c, f3(pc['cv_r2']), f3(pc['cv_r2_with_duplicates'])] +
                        [f3(pc['fits_dedup'][m]['cv_r2']) for m in ('famP, famG*n^3', 'famP, famG, famG*n^3')])
        L.append(table(['code', 'spec model CV-R2 (dedup; decisive)', 'spec model CV-R2 (with duplicates)',
                        'famP + famG*n^3 CV-R2 (reported)', 'famP + famG + famG*n^3 CV-R2 (reported)'], rows))
        L.append('\ncount-degenerate (decisive): %s; with duplicates: %s; family-aware models would fire: %s' % (
            E['count_degenerate'], E['count_degenerate_with_duplicates'],
            json.dumps({k: v2 for k, v2 in E.items() if k.startswith('family_model')})))
        L.append('\nDuplicate check (surplus of duplicate, surplus of corpus original) C1: ' + json.dumps(E['per_code']['C1']['duplicate_values']))
        rows = []
        for s in sorted(E['per_code']['C1']['points']):
            rows.append([s] + [f1(E['per_code'][c]['points'][s]['surplus_on']) for c in PRIMARY] +
                        [E['per_code']['C1']['points'][s]['n'], E['per_code']['C1']['points'][s]['pairs'], E['per_code']['C1']['points'][s]['P']])
        L.append('\n' + table(['system'] + ['s_k(EC) %s' % c for c in PRIMARY] + ['n', 'pairs', 'P'], rows))
    else:
        L.append('\n## EC scaling degeneracy (7.3)\n\nNot run: EC is not constraint-type at the primary setting (spec: only if EC is constraint-type).')
    H = R['hypothesis_iii']
    L.append('\n## Hypothesis (iii)\n')
    L.append(table(['law', 'median kappa = V+_mid/V_mid'], [[f, f3(H['kappa_median'][f])] for f in LAW9]))
    L.append('\nSpearman(kappa, hypothesised order) per code: %s; median-kappa Spearman: %s; PC/LC abbreviation: %s; '
             'definition outranks a conservation law: %s; REFUTED: %s' % (
                 json.dumps({k: round(x, 3) for k, x in H['spearman_per_code'].items()}), f3(H['spearman_median']),
                 H['PC_or_LC_abbreviation'], H['definition_outranks_conservation'], H['refuted']))
    L.append('\n## Prior predictions\n')
    L.append(table(['prediction', 'hit', 'observed'], [[p['prediction'], p['hit'], json.dumps(p['observed'], default=str)[:200]]
                                                      for p in R['prior_predictions_hit']]))
    dev = open(os.path.join(HERE, 'DEVIATIONS.txt')).read() if os.path.exists(os.path.join(HERE, 'DEVIATIONS.txt')) else ''
    L.append('\n## Deviations and implementation choices\n\n```\n' + dev + '\n```\n')
    L.append('\nRuntime: %.0f s total.' % R['runtime_s_total'])
    with open(md_path, 'w') as fh:
        fh.write('\n'.join(L) + '\n')
    with open(json_path, 'w') as fh:
        json.dump(R, fh, indent=1, default=str)
