"""Writes research/pilot_e/results.md and results.json from the analysis dict."""
import json, math, os
from common import LAW9, PHYS7, PRIMARY, LEVELS, HERE


def f1(x):
    if x is None:
        return 'n/a'
    if isinstance(x, float) and (math.isinf(x) or math.isnan(x)):
        return str(x)
    return '%.1f' % x


def f3(x):
    if x is None:
        return 'n/a'
    if isinstance(x, float) and (math.isinf(x) or math.isnan(x)):
        return str(x)
    return '%.3f' % x


def table(header, rows):
    out = ['| ' + ' | '.join(header) + ' |', '|' + '---|' * len(header)]
    for r in rows:
        out.append('| ' + ' | '.join(str(x) for x in r) + ' |')
    return '\n'.join(out)


def write(R, md_path, json_path):
    L = []
    v = R['verdict']
    L.append('# Pilot E-v1 results ("two kinds of compression")\n')
    L.append('Frozen spec: `pilot_v1/SPEC.md`, sha256 `%s`. All numbers regenerated by `python3 pilot_v1/run_all.py`.\n' % R['spec_sha256'])
    L.append('## Verdict\n')
    L.append(table(['item', 'result'], [
        ['K1 (code dependence)', 'FIRED' if v['K1']['fired'] else 'not fired'],
        ['K1 sub-tests fired', ', '.join(v['K1']['subtests']) or '-'],
        ['K1-fragile label', v['K1']['fragile']],
        ['K2-deg-R (Track R degeneracy)', 'FIRED' if v['K2_deg_R'] else 'not fired'],
        ['K2-deg-G (Track G degeneracy)', 'FIRED' if v['K2_deg_G'] else 'not fired'],
        ['K2-collapse', v['K2_collapse']],
        ['validity gate', json.dumps(v['K2_collapse_gate'])],
        ['constraint-type physical laws (primary setting)', v['constraint_type_physical_laws']],
        ['K2 overall', 'FIRED' if v['K2_overall'] else 'not fired'],
        ['candidate', v['candidate']],
        ['hypothesis (iii)', 'REFUTED' if R['hypothesis_iii']['refuted'] else 'not refuted'],
    ]))
    if v.get('note_indeterminate'):
        L.append('\nNote: ' + v['note_indeterminate'])
    L.append('\n## Unit tests (section 9)\n')
    L.append(table(['test', 'passed', 'detail'], [[k, d['passed'], json.dumps(d['detail'], default=str)[:160]]
                                                  for k, d in sorted(R['unit_tests'].items())]))
    # ---------------- Track G values
    T = R['tables']
    L.append('\n## Track G: per-law values (bits; positive = the law shortens the corpus)\n')
    L.append('Phi = exact Shapley over the 512-theory lattice; add = L(0)-L({f}); loo = L(LAW9\\f)-L(LAW9); '
             'mid = (add+loo)/2. Miner off, EC decoder uncharged unless stated.\n')
    for tag in ['C1-D1-B16', 'C2-D1-B16', 'C3-D1-B16', 'C4-D1-B16', 'C1-D0-B16', 'C2-D0-B16', 'C3-D0-B16', 'C4-D0-B16',
                'C1-D2-B16', 'C2-D2-B16', 'C3-D2-B16', 'C4-D2-B16', 'C4-D1-B8', 'C4-D1-B32', 'C4-D0-B8', 'C4-D0-B32',
                'C4-D2-B8', 'C4-D2-B32', 'C5-D0-B16', 'C5-D1-B16', 'C5-D2-B16']:
        t = T[tag]
        L.append('\n### %s   (L(S|0) = %s, L(S|LAW9) = %s, dec(EC) = %s)\n' % (tag, f1(t['L0']), f1(t['Lfull']), f1(t['dec'])))
        rows = []
        for f in LAW9:
            x = t['values'][f]
            xc = t['values_charged'][f]
            rows.append([f, f1(x['Phi']), f1(x['add']), f1(x['loo']), f1(x['mid']), f1(xc['Phi']), f1(xc['mid']),
                         f1(t['law_single'][f])])
        L.append(table(['law', 'Phi', 'V_add', 'V_loo', 'V_mid', 'Phi (EC charged)', 'V_mid (charged)', 'L_c(f)'], rows))
    c8 = R['K1']['C8']
    L.append('\n### C8 (lzma proxy on C1-chosen D1 representations)  L(S|0)=%s, L(S|LAW9)=%s\n' % (f1(c8['L0']), f1(c8['Lfull'])))
    L.append(table(['law', 'Phi_C8'], [[f, f1(c8['Phi'][f])] for f in LAW9]))
    L.append('\nSpearman C8 vs primary codes: %s; top law C8: %s' % (json.dumps({k: round(x, 3) for k, x in c8['spearman'].items()}), c8['top']))
    # ---------------- K1
    K1 = R['K1']
    L.append('\n## K1 (section 6)\n')
    for name in ('primary', 'machine', 'precision'):
        k = K1[name]
        L.append('\n**K1-%s**: fired = %s (criterion a: %s, criterion b: %s); min rho = %s' % (
            name, k['fired'], k['fired_a'], k['fired_b'], f3(k['min_rho'])))
        L.append('\n' + table(['pair', 'Spearman rho'], [[p, f3(x)] for p, x in k['pairs'].items()]))
        L.append('\nTop law per code: ' + json.dumps(k['tops']))
        if k['flips']:
            L.append('\nTop-law flips (Phi_b(top_a) < 0.9 max Phi_b):\n' + table(
                ['a', 'b', 'top_a', 'Phi_b(top_a)', 'max Phi_b', 'top_b'],
                [[x['a'], x['b'], x['top_a'], f1(x['Phi_b_top_a']), f1(x['max_b']), x['top_b']] for x in k['flips']]))
    b = K1['bootstrap']
    L.append('\n**Bootstrap (1000 resamples of systems, per-system decomposition, miner off)**\n')
    for name in ('primary', 'machine'):
        L.append('\n%s: P(top flip) = %s, P(K1 fires) = %s; 95%% CI of rho: %s' % (
            name, f3(b[name]['P_flip']), f3(b[name]['P_fire']),
            json.dumps({k: [round(x[0], 3), round(x[1], 3)] for k, x in b[name]['rho_CI95'].items()})))
    L.append('\nReported (not decisive): 7-law primary min rho = %s, flips = %d; EC-charged primary min rho = %s, flips = %d; '
             'C5 vs primary rho = %s.' % (f3(K1['primary_7law']['min_rho']), len(K1['primary_7law']['flips']),
                                         f3(K1['primary_charged']['min_rho']), len(K1['primary_charged']['flips']),
                                         json.dumps({k: round(x, 3) for k, x in K1['C5_vs_primary'].items()})))
    L.append('\nPrimary-code test repeated at each machine level: ' + json.dumps(
        {lv: dict(min_rho=round(K1['primary_by_level'][lv]['min_rho'], 3), tops=K1['primary_by_level'][lv]['tops'],
                  fired=K1['primary_by_level'][lv]['fired']) for lv in LEVELS}))
    L.append('\nMachine-axis test per code: ' + json.dumps(
        {c: dict(min_rho=round(K1['machine_by_code'][c]['min_rho'], 3), tops=K1['machine_by_code'][c]['tops'],
                 fired=K1['machine_by_code'][c]['fired']) for c in PRIMARY}))
    if R.get('miner_on_shapley'):
        m = R['miner_on_shapley']
        L.append('\n**Miner-on Shapley (secondary, D1)**\n')
        L.append(table(['law'] + PRIMARY, [[f] + [f1(m['Phi_plus'][c][f]) for c in PRIMARY] for f in LAW9]))
        L.append('\nminer-on K1-style test: min rho = %s, tops = %s, flips = %d' % (
            f3(m['K1_test']['min_rho']), json.dumps(m['K1_test']['tops']), len(m['K1_test']['flips'])))
    # ---------------- K2 deg G
    G = R['K2_deg_G']
    L.append('\n## K2-deg-G (section 7.2)\n')
    L.append(table(['code', 'M1 CV-R2 (LOSO)', 'M1 in-sample R2', 'n cells', 'beta_r', 'beta_u', 'beta_P', 'beta_n',
                    'law-level CV-R2 (LOLO)', 'law-level R2'],
                   [[c, f3(G['M1'][c]['cv_r2']), f3(G['M1'][c]['r2']), G['M1'][c]['n'],
                     f3(G['M1'][c]['coef']['beta_r']), f3(G['M1'][c]['coef']['beta_u']), f3(G['M1'][c]['coef']['beta_P']),
                     f3(G['M1'][c]['coef']['beta_n']), f3(G['lawlevel'][c]['cv_r2']), f3(G['lawlevel'][c]['r2'])]
                    for c in PRIMARY]))
    L.append('\nM1 fired: %s; law-level fired: %s; K2-deg-G fired: %s' % (G['M1_fired'], G['lawlevel_fired'], G['fired']))
    L.append('\nLaw-level coefficients: ' + json.dumps({c: {k: round(x, 3) for k, x in G['lawlevel'][c]['coef'].items()} for c in PRIMARY}))
    L.append('\nM1 law fixed effects: ' + json.dumps({c: {k: round(x, 2) for k, x in G['M1'][c]['coef'].items() if k.startswith('FE')} for c in PRIMARY}))
    # ---------------- K2 deg R
    Rr = R['K2_deg_R']
    tr = R['trackR']
    L.append('\n## Track R and K2-deg-R (sections 1.7, 7.4)\n')
    L.append('Valid cells (law equations satisfied by the linearized ground truth):\n')
    L.append(table(['system', 'law', 'N', 'P', 'codim', 'r_fk', 'I_R1(b=4)', 'I_R1(b=8)', 'I_R1(b=16)', 'I_R2', 'I_R3',
                    'log2 index', 'I_R4(N=100)', 'I_R4(N=1000)', 'monomial slots'],
                   [[c['sid'], c['law'], c['N'], c['P'], c['codim'],
                     [x['r'] for x in Rr['r_vs_codim'] if x['sid'] == c['sid'] and x['law'] == c['law']][0],
                     f1(c['I_R1'][4]), f1(c['I_R1'][8]), f1(c['I_R1'][16]), f1(c['I_R2']), f1(c['I_R3']),
                     f3(c['log2_index']), f1(c['I_R4'][100]), f1(c['I_R4'][1000]), '%d/%d' % (c['monomial_slots'], c['P'])]
                    for c in tr['cells']]))
    L.append('\nExcluded cells: ' + json.dumps([(c['sid'], c['law'], round(c['resid'], 4), c['note']) for c in tr['excluded']]))
    L.append('\nReported only: ' + json.dumps([(c['sid'], c['law'], c['codim']) for c in tr['reported_only']]))
    L.append('\n' + table(['R code', 'per-cell R2 (I ~ beta r, no intercept; centered)', 'uncentered R2', 'beta',
                           'R2 of I ~ beta*codim'],
                          [[n, f3(Rr['percell'][n]['r2']), f3(Rr['percell'][n]['r2_uncentered']), f3(Rr['percell'][n]['beta']),
                            f3(Rr['percell'][n]['r2_vs_codim'])] for n in ('R1', 'R2', 'R3', 'R4')] +
                          [[n + ' (secondary)', f3(x['r2']), f3(x['r2_uncentered']), f3(x['beta']), f3(x['r2_vs_codim'])]
                           for n, x in Rr['secondary'].items()]))
    L.append('\nK2-deg-R fired: %s' % Rr['fired'])
    L.append('\nV^R_c(f) = sum_k I_c(f,k) - L_C1(f):\n')
    L.append(table(['law'] + list(Rr['VR'].keys()), [[f] + [f1(Rr['VR'][n][f]) for n in Rr['VR']] for f in
                                                      ['EC', 'PC', 'LC', 'N3', 'N2', 'HK', 'UG', 'DIST', 'KE']]))
    L.append('\nLaw-level regressions V^R ~ sum r: ' + json.dumps({n: dict(laws=x['laws'], r2=round(x['r2'], 3)) for n, x in Rr['lawlevel'].items()}))
    L.append('\nMach block (N2, corpus level): ' + json.dumps(tr['mach']))
    L.append('\nPOS (Track R, reported): ' + json.dumps(tr['pos']))
    # ---------------- K2 collapse
    L.append('\n## K2-collapse (section 8)\n')
    L.append('constraint surplus = V+_mid (miner on); abbreviation share = V_mid - V+_mid (recovered by the generic miner).\n')
    for name, st in R['K2_collapse'].items():
        L.append('\n### setting: %s   (tau: %s)\n' % (name, json.dumps({c: round(x, 1) for c, x in st['tau'].items()})))
        rows = []
        for f in LAW9:
            row = [f]
            for c in PRIMARY:
                x = st['per_code'][c][f]
                row.append('%s / %s / %s (%s)' % (f1(x['V_mid']), f1(x['Vplus_mid']), f1(x['V_mid'] - x['Vplus_mid']), x['label']))
            row.append(st['labels'][f])
            rows.append(row)
        L.append(table(['law'] + ['%s: V_mid / V+_mid / abbrev (label)' % c for c in PRIMARY] + ['label (>=3 of 4)'], rows))
        if 'POS' in st:
            p = st['POS']
            L.append('\nPOS (C4): V_mid = %s, V+_mid = %s, label = %s; detail %s' % (f1(p['V_mid']), f1(p['Vplus_mid']), p['label'],
                                                                                  json.dumps(p['detail'])))
    if R.get('EC_scaling'):
        E = R['EC_scaling']
        L.append('\n## EC scaling degeneracy (7.3)\n')
        L.append(table(['code', 'CV-R2 (LOSO)', 'R2', 'coef [1, n, pairs, P, famG]'],
                       [[c, f3(E['per_code'][c]['cv_r2']), f3(E['per_code'][c]['r2']), json.dumps([round(x, 2) for x in E['per_code'][c]['coef']])]
                        for c in PRIMARY]))
        L.append('\ncount-degenerate: %s' % E['count_degenerate'])
        rows = []
        for s in sorted(E['per_code']['C1']['points']):
            rows.append([s] + [f1(E['per_code'][c]['points'][s]['surplus_on']) for c in PRIMARY] +
                        [E['per_code']['C1']['points'][s]['n'], E['per_code']['C1']['points'][s]['pairs'], E['per_code']['C1']['points'][s]['P']])
        L.append('\n' + table(['system'] + ['s_k(EC) %s' % c for c in PRIMARY] + ['n', 'pairs', 'P'], rows))
    else:
        L.append('\n## EC scaling degeneracy (7.3)\n\nNot run: EC is not constraint-type at the primary setting (spec: only if EC is constraint-type).')
    H = R['hypothesis_iii']
    L.append('\n## Hypothesis (iii)\n')
    L.append(table(['law', 'median kappa = V+_mid/V_mid'], [[f, f3(H['kappa_median'][f])] for f in LAW9]))
    L.append('\nSpearman(kappa, hypothesised order) per code: %s; median-kappa Spearman: %s; PC/LC abbreviation: %s; '
             'definition outranks a conservation law: %s; REFUTED: %s' % (
                 json.dumps({k: round(x, 3) for k, x in H['spearman_per_code'].items()}), f3(H['spearman_median']),
                 H['PC_or_LC_abbreviation'], H['definition_outranks_conservation'], H['refuted']))
    L.append('\n## Prior predictions\n')
    L.append(table(['prediction', 'hit', 'observed'], [[p['prediction'], p['hit'], json.dumps(p['observed'], default=str)[:200]]
                                                      for p in R['prior_predictions_hit']]))
    dev = open(os.path.join(HERE, 'DEVIATIONS.txt')).read() if os.path.exists(os.path.join(HERE, 'DEVIATIONS.txt')) else ''
    L.append('\n## Deviations and implementation choices\n\n```\n' + dev + '\n```\n')
    L.append('\nRuntime: %.0f s total.' % R['runtime_s_total'])
    with open(md_path, 'w') as fh:
        fh.write('\n'.join(L) + '\n')
    with open(json_path, 'w') as fh:
        json.dump(R, fh, indent=1, default=str)
